# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: LAIR @ NYU
# Description of the Site
description: Lab for Autonomous and Intelligent Robotics
# URL of Image of the Site
site-image: /LAIR/assets/images/AUV.jpg
# Keywords of the Site
site-keywords: Robotics, AUV, Multi-Robot
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /LAIR/assets/images/AUV.jpg

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: c.clark@nyu.edu
facebook_username: 
twitter_username: 
instagram_username:  
linkedin_username: 
github_username: 
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Christopher Clark
# URL for the Image of the Author
author-image: /LAIR/assets/images/ClarkIver2.jpg
# 60 Words About the Author
author-about: The Lab for Autonomous And Intelligent Robots is a university research lab at NYU that strives to develop new robotics algorithms, ML models, and control systems motivated by in-the-wild applications. Originally focussing on multi-robot systems and motion planning, the lab's work has been applied to marine biology, archaeology, autonomous driving, security systems, and oceanography. The LAIR has travelled with Professor Christopher Clark career and hence has had many home institutions including the University of Waterloo, Cal Poly SLO, Princeton University, Harvey Mudd College, and now NYU.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://engineering.nyu.edu/faculty/christopher-clark

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/









